# uses data generated by hartree calculations in phase_diagram.jl path
# to compute the observable Drude, LMC_orbital, LMC_spin or QAH

for (i, a) in enumerate(ARGS)
    @info "ARGS[$i] = $a"
end

job_id = parse(Int, ARGS[1])
jobs_num = parse(Int, ARGS[2])
PID = ARGS[3]
phasediagPID = ARGS[4]    # PID of the process that generated the hartree mus and nss out of interpolated data with PID interpPID
evals = parse(Int, ARGS[5])
T = parse(Float64, ARGS[6]) # temperature a <= eta/kb ~ 1K, since this is really a T=0 limit and in the Phase diagram T = 0 and there are only broadening effects
tau = parse(Float64, ARGS[7])
which_observable = ARGS[8]  # Drude, LMC_orbital, LMC_spin, or QAH


println("Importing interpolating data")

using JLD2, CSV, DataFrames, Interpolations, LMC, Optics_in_the_length_gauge, LinearAlgebra

# import data from the hartree calculation and presets
pd_filestring = pwd() * "/Data/PhaseDiagrams/" * string(phasediagPID) * "/" * string(job_id)
@load pd_filestring * "/pd_data.jld" nu_list mus nss Ezs
@load pd_filestring  * "/presets.jld" PD_presets dataPID


#define the observable and its presets
if which_observable == "Drude"
    obs = drude_conductivity
    presets(; ξ, Ez, μ) = 
        xx_drude_presets(PD_presets.N, Params_rhombohedral(PD_presets.p, ξ = ξ, μ = μ, Delta_Ez = Ez), 
            T = T, τ = tau, evals = evals)
elseif which_observable == "LMC_orbital" # note generalised to spin!!!!!!
    obs = linear_magneto_conductivity_orbital
    presets(; ξ, Ez, μ) = xxx_lmc_presets(PD_presets.N, 
        Params_rhombohedral(PD_presets.p, ξ = ξ, μ = μ, Delta_Ez = Ez),
        T = T, τ = tau, evals = evals, berry_contribution = true,
        omm_contribution = true, fermi_surface = false, with_shift= false)

elseif which_observable == "LMC_spin" #
    obs = linear_magneto_conductivity_spin
    presets(; ξ, Ez, μ) = Planar_σijk_presets_spin([1I,1I,1I],
        xxx_lmc_presets(PD_presets.N, 
            Params_rhombohedral(PD_presets.p, ξ = ξ, μ = μ, Delta_Ez = Ez),
            T = T, τ = tau, evals = evals, berry_contribution = true,
            omm_contribution = true, fermi_surface = false, with_shift= false))

elseif which_observable == "QAH" 
    obs = σij_anomalous_hall
    presets(; ξ, Ez, μ) = 
        qah_presets(PD_presets.N, :x, :y, Params_rhombohedral(PD_presets.p, ξ = ξ, μ = μ, Delta_Ez = Ez),
            T = T, evals = evals) 
else throw(ArgumentError("observable not allowed"))
end


print("Building structs...")


print("Computation...")

obs_list = Ez_map_eval(obs, presets, mus[1], Ezs[1], nu_list)

print("Storing...")

new_data_folder = pwd() * "/Data/$(which_observable)/" * string(PID) * "/" * string(job_id)
mkpath(new_data_folder)

comp_struct = Observable_computation(job_id, jobs_num, PID, dataPID, 
    phasediagPID, evals, T, tau, which_observable)

@save new_data_folder * "/presets.jld" comp_struct
@save new_data_folder * "/data.jld" Ezs nu_list obs_list mus nss

print("Success!")

str = pwd() * "/slurm-" * string(PID) * "." * string(job_id)
mv(str * ".out", new_data_folder * "/output.out")
mv(str * ".err", new_data_folder * "/error.err")