abcplotbandsk(kws...) = not_defined(kws...)
abcNplotbandsk(kws...) = not_defined(kws...)
abcplotbands!(kws...) = not_defined(kws...)
half_metal_dos(kws...) = not_defined(kws...)
quarter_metal_dos(kws...) = not_defined(kws...)
half_metal_plotbands(kws...) = not_defined(kws...)
quarter_metal_plotbands(kws...) = not_defined(kws...)
spinfull_plotbands(kws...) = not_defined(kws...)
spinfull_plotbands!(kws...) = not_defined(kws...)
plotmap(kws...) = not_defined(kws...)
plotmap!(kws...) = not_defined(kws...)
plot_dos!(kws...) = not_defined(kws...)
plot_characters(kws...) = not_defined(kws...)
plot_phasediagrams(kws...) = not_defined(kws...)
plot_cluster_bandsanddos(kws...) = not_defined(kws...)
spinfull_plotbandsanddos(kws...) = not_defined(kws...)

function not_defined(args...)
    error("Load CairoMakie to enable plotting")
end
